node('docker') {

 stage('Preparation (Checking out)') {
       git branch: 'akarzhou2', url: 'https://github.com/alexeikorzhov/docker.git'
         }

 stage ('Building docker gradle image'){
	  docker.build ('gradle', '-f docker-2/gradle.Dockerfile .')
            }
 dir('docker-2'){
    stage ('Building code'){
        docker.image('gradle:latest').inside {
             sh 'gradle build'
    	    }
	       }

	stage ('Deployment'){
       	        sh 'docker-compose up -d'
	            }

	stage ('Check'){

	         sh 'sleep 8 && curl -IL http://127.17.0.2:8080'
             sh 'docker-compose stop jar && docker-compose rm -f jar'
             }

	        }

 }
